# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 9
  - name: Experience
    url: experience/
    weight: 10
#  - name: Papers
#    url: /#papers
#    weight: 11
#  - name: PPG Calon Guru 2024
#    url: /tags
#    weight: 12
#  - name: Talks
#    url: /#talks
#    weight: 12
  - name: Blog
    url: /#news
    weight: 50
  - name: PPG Calon Guru 2024
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
